from typing import Protocol, Optional, Dict, Any, Tuple, List
from dataclasses import dataclass

@dataclass
class Usuario:
    nombre: str
    es_owner: bool = False

# ---------------------------------------------------------
# Interfaces de Infraestructura y Servicios Base (DIP, OCP)
# ---------------------------------------------------------

class RepositorioArchivos(Protocol):
    def guardar(self, nombre: str, fat_entry: Dict[str, Any]) -> None: ...
    def buscar(self, nombre: str) -> Optional[Dict[str, Any]]: ...
    def listar(self, mostrar_papelera: bool = False) -> List[Dict[str, Any]]: ...
    def borrar(self, nombre: str) -> bool: ...

class AlmacenamientoBloques(Protocol):
    def guardar_bloques(self, contenido: str, archivo_nombre: str) -> Optional[str]: ...
    def leer_bloques(self, referencia: str) -> str: ...
    def eliminar_bloques(self, referencia: str) -> None: ...

class PoliticaPermisos(Protocol):
    def puede_leer(self, usuario: str, fat_entry: Dict[str, Any]) -> bool: ...
    def puede_escribir(self, usuario: str, fat_entry: Dict[str, Any]) -> bool: ...
    def puede_administrar(self, usuario: str, fat_entry: Dict[str, Any]) -> bool: ...
    def es_admin(self, usuario: str) -> bool: ...

class ServicioAutenticacion(Protocol):
    def autenticar(self, nombre: str, password: str) -> Optional[Usuario]: ...


# ---------------------------------------------------------
# Interfaces de Dominio segregadas (ISP)
# ---------------------------------------------------------

class LectorArchivos(Protocol):
    def listar_archivos(self, mostrar_papelera: bool = False) -> List[Dict[str, Any]]: ...
    def abrir_archivo(self, nombre_archivo: str, usuario: str) -> Tuple[str, Optional[Dict[str, Any]]]: ...

class EditorArchivos(Protocol):
    def crear_archivo(self, nombre: str, contenido: str, owner: str) -> Tuple[str, bool]: ...
    def modificar_archivo(self, nombre_archivo: str, nuevo_contenido: str, usuario: str) -> str: ...

class GestorPapelera(Protocol):
    def eliminar_archivo(self, nombre_archivo: str) -> str: ...
    def recuperar_archivo(self, nombre_archivo: str) -> str: ...

class GestorPermisos(Protocol):
    def asignar_permisos(self, nombre_archivo: str, usuario_objetivo: str, lectura: bool, escritura: bool, owner: str) -> str: ...
